version: "3.8"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: enam_server
    ports:
      - "8000:8000"
    volumes:
      # Syncs your local folder with the container for hot-reloading code changes
      - ./server:/app/server
    env_file:
      - .env
    networks:
      - enam_network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: enam_client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      # PREVENT overwriting node_modules inside container with local host version
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000/api/v1
    depends_on:
      - server
    networks:
      - enam_network

networks:
  enam_network:
    driver: bridge
